const questions = [
["q1","Você já realiza ou já realizou atividades relacionadas ao controle do almoxarifado?","single",["Sim","Não"]],
["q2","Há quanto tempo você realiza atividades relacionadas ao almoxarifado?","single",["Menos de 6 meses","6 meses a 1 ano","1 a 2 anos","Mais de 2 anos","Não realizo essa atividade"]],
["q3","Como o controle dos produtos é realizado atualmente?","single",["Anotações em papel","Planilha","Sistema informatizado","Mais de uma dessas formas","Outro"]],
["q4","Com que frequência é necessário registrar a entrada ou saída de produtos?","single",["Várias vezes ao dia","Uma vez ao dia","Algumas vezes por semana","Raramente","Não sei informar"]],
["q5","Quais informações normalmente precisam ser registradas quando um produto entra ou sai?","multi",["Nome do produto","Quantidade","Data","Responsável","Outra"]],
["q6","Como você considera o processo atual de registro dos produtos?","scale",["1","2","3","4","5"]],
["q7","Quanto tempo, aproximadamente, você acredita gastar para registrar uma movimentação de estoque?","single",["Menos de 5 minutos","5 a 10 minutos","10 a 20 minutos","Mais de 20 minutos","Não sei informar"]],
["q8","Você considera o controle atual do estoque organizado?","scale",["1","2","3","4","5"]],
["q9","Você já teve dificuldade para registrar corretamente a entrada ou saída de algum produto?","single",["Nunca","Raramente","Às vezes","Frequentemente","Sempre"]],
["q10","Qual é a principal dificuldade encontrada no controle dos produtos?","single",["Falta de tempo","Muitos produtos para controlar","Anotações","Erros na contagem","Falta de organização","Dificuldade com planilhas","Outra"]],
["q11","Você já encontrou alguma diferença entre a quantidade registrada e a quantidade realmente existente no estoque?","single",["Nunca","Raramente","Às vezes","Frequentemente","Não sei informar"]],
["q12","Com que frequência você precisa conferir novamente as quantidades dos produtos?","single",["Nunca","Raramente","Às vezes","Frequentemente","Sempre"]],
["q13","Você considera importante manter o estoque atualizado?","single",["Muito importante","Importante","Mais ou menos importante","Pouco importante","Nada importante"]],
["q14","Você acredita que um controle de estoque mais organizado poderia facilitar seu trabalho?","single",["Sim","Talvez","Não"]],
["q15","Você já utilizou alguma planilha para registrar informações de estoque?","single",["Sim, tenho facilidade","Sim, mas tenho alguma dificuldade","Já utilizei poucas vezes","Nunca utilizei"]],
["q16","Como você avalia sua facilidade para utilizar ferramentas digitais, como celular, computador ou planilhas?","scale",["1","2","3","4","5"]],
["q17","Você teria facilidade para tirar uma foto de uma ficha preenchida pelo celular?","single",["Sim","Talvez","Não"]],
["q18","Você teria facilidade para enviar essa foto por WhatsApp ou outro aplicativo?","single",["Sim","Talvez","Não"]],
["q19","O que você acha da ideia de preencher uma ficha e depois enviar uma foto para que as informações sejam registradas no sistema?","single",["Muito boa","Boa","Não tenho opinião","Ruim","Muito ruim"]],
["q20","Você acredita que esse processo poderia diminuir o trabalho manual de registro?","single",["Sim","Talvez","Não"]],
["q21","Você acha importante que a quantidade em estoque seja atualizada automaticamente após o registro de uma entrada ou saída?","single",["Muito importante","Importante","Indiferente","Pouco importante","Nada importante"]],
["q22","Qual seria a principal vantagem de um sistema que pudesse identificar as informações da ficha através de uma foto?","single",["Economizar tempo","Diminuir erros","Facilitar o registro","Melhorar a organização","Todas as anteriores","Outra"]],
["q23","Qual seria sua maior preocupação ao utilizar esse tipo de sistema?","single",["A foto não ser reconhecida corretamente","Errar ao preencher a ficha","Ter dificuldade para enviar a foto","Não saber utilizar o sistema","Não tenho preocupação","Outra"]],
["q24","O que você espera que o novo sistema melhore no controle do almoxarifado?","text",[]],
["q25","Existe alguma sugestão ou recurso que você gostaria que o novo sistema tivesse?","text",[]]
];