-- BANCO DE DADOS DO SISTEMA DE PESQUISA DO TCC
-- Execute este SQL no Supabase > SQL Editor.

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  stage text not null check (stage in ('antes','depois')),
  answers jsonb not null
);

alter table public.responses enable row level security;

-- Qualquer pessoa pode ENVIAR uma resposta, mas não pode ler as respostas.
drop policy if exists "public insert responses" on public.responses;
create policy "public insert responses"
on public.responses for insert
to anon
with check (true);

-- Somente usuários autenticados podem ler as respostas.
drop policy if exists "authenticated read responses" on public.responses;
create policy "authenticated read responses"
on public.responses for select
to authenticated
using (true);

-- Não damos update/delete ao público. O painel usa apenas leitura.
